# Utiliser une image de base officielle Node.js
FROM node:14

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install
COPY . .

# Copier le fichier .env
COPY .env .env

# Construire l'application
RUN npm run build

# Exposer le port de l'application
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]
