version: '3.8'

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    command: >
      bash -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      echo \"from django.contrib.auth import get_user_model; User = get_user_model(); 
      User.objects.filter(username='${DJANGO_SUPERUSER_USERNAME}').exists() or 
      User.objects.create_superuser('${DJANGO_SUPERUSER_USERNAME}', '${DJANGO_SUPERUSER_EMAIL}', '${DJANGO_SUPERUSER_PASSWORD}')\" | python manage.py shell &&
      gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
      "
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt  # Montage des certificats Let's Encrypt
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt  # Montage des certificats Let's Encrypt
      - ./frontend/build:/usr/share/nginx/html  # Montage du répertoire de build de React
    networks:
      - app_network
    depends_on:
      - django
      - react
    restart: unless-stopped

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
