FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt gunicorn

RUN apt-get update && apt-get install -y postgresql-client

COPY . .

ENV DJANGO_SETTINGS_MODULE=backend.settings

EXPOSE 8000

CMD ["gunicorn", "--bind", "127.0.0.1:8000", "backend.wsgi:application"]
