export const EDUCATION_LIST_REQUEST = 'EDUCATION_LIST_REQUEST'
export const EDUCATION_LIST_SUCCESS = 'EDUCATION_LIST_SUCCESS'
export const EDUCATION_LIST_FAIL = 'EDUCATION_LIST_FAIL'

export const EDUCATION_DETAILS_REQUEST = 'EDUCATION_DETAILS_REQUEST'
export const EDUCATION_DETAILS_SUCCESS = 'EDUCATION_DETAILS_SUCCESS'
export const EDUCATION_DETAILS_FAIL = 'EDUCATION_DETAILS_FAIL'

export const EDUCATION_CREATE_REVIEW_REQUEST = 'EDUCATION_CREATE_REVIEW_REQUEST'
export const EDUCATION_CREATE_REVIEW_SUCCESS = 'EDUCATION_CREATE_REVIEW_SUCCESS'
export const EDUCATION_CREATE_REVIEW_FAIL = 'EDUCATION_CREATE_REVIEW_FAIL'
export const EDUCATION_CREATE_REVIEW_RESET = 'EDUCATION_CREATE_REVIEW_RESET'