export const SOCIAL_LINK_LIST_REQUEST = 'SOCIAL_LINK_LIST_REQUEST'
export const SOCIAL_LINK_LIST_SUCCESS = 'SOCIAL_LINK_LIST_SUCCESS'
export const SOCIAL_LINK_LIST_FAIL = 'SOCIAL_LINK_LIST_FAIL'

export const SOCIAL_LINK_DETAILS_REQUEST = 'SOCIAL_LINK_DETAILS_REQUEST'
export const SOCIAL_LINK_DETAILS_SUCCESS = 'SOCIAL_LINK_DETAILS_SUCCESS'
export const SOCIAL_LINK_DETAILS_FAIL = 'SOCIAL_LINK_DETAILS_FAIL'

export const SOCIAL_LINK_CREATE_REVIEW_REQUEST = 'SOCIAL_LINK_CREATE_REVIEW_REQUEST'
export const SOCIAL_LINK_CREATE_REVIEW_SUCCESS = 'SOCIAL_LINK_CREATE_REVIEW_SUCCESS'
export const SOCIAL_LINK_CREATE_REVIEW_FAIL = 'SOCIAL_LINK_CREATE_REVIEW_FAIL'
export const SOCIAL_LINK_CREATE_REVIEW_RESET = 'SOCIAL_LINK_CREATE_REVIEW_RESET'