FROM nginx:alpine

# Copier la configuration Nginx personnalisée
COPY default.conf /etc/nginx/conf.d/default.conf

# Exposer les ports 80 et 443
EXPOSE 80
EXPOSE 443

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
