# Generated by Django 4.2.7 on 2024-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('imageSrc', models.ImageField(upload_to='education_images/')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='iconsSrc',
        ),
        migrations.AddField(
            model_name='experience',
            name='imageSrc',
            field=models.ImageField(default='default_image.jpg', upload_to='experience_images/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
