# Generated by Django 4.2.7 on 2024-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0002_education_remove_experience_iconssrc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('terminated', 'Terminated')], default='ongoing', max_length=20),
        ),
    ]
