# Generated by Django 4.2.7 on 2024-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0003_remove_experience_location_experience_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
