# Generated by Django 5.0.1 on 2024-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0004_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('terminated', 'Terminated')], default='ongoing', max_length=20),
        ),
    ]
