# Generated by Django 5.0.1 on 2024-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0006_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(),
        ),
    ]
