# Generated by Django 5.0.6 on 2024-05-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0010_gptconversation_user_delete_gptmessagehistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPTConversation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
