# Generated by Django 5.0.6 on 2024-05-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0011_delete_gptconversation_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='imageSrc',
            field=models.ImageField(upload_to='media/education_images/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='imageSrc',
            field=models.ImageField(default='default_image.jpg', upload_to='media/experience_images/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(upload_to='media/presentation_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageSrc',
            field=models.ImageField(upload_to='media/project_images/'),
        ),
    ]
