# Generated by Django 5.0.6 on 2024-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0014_presentation_age_presentation_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(default='', max_length=255),
        ),
    ]
