# Generated by Django 5.0.6 on 2024-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0016_remove_sociallink_iconsrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='iconSrc',
            field=models.ImageField(default='social_icons', max_length=255, upload_to=''),
        ),
    ]
