# Generated by Django 5.0.6 on 2024-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_portfolio_app', '0017_remove_sociallink_icon_class_sociallink_iconsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='iconSrc',
            field=models.FileField(default='social_icons', max_length=255, upload_to=''),
        ),
    ]
